name: segearth
channels:
  - defaults
  - nvidia
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - cuda-cccl=12.1.109=0
  - cuda-cccl_linux-64=12.9.27=0
  - cuda-crt-dev_linux-64=12.9.86=0
  - cuda-cudart=12.9.79=0
  - cuda-cudart-dev=12.1.105=0
  - cuda-cudart-dev_linux-64=12.9.79=0
  - cuda-cudart-static_linux-64=12.9.79=0
  - cuda-cudart_linux-64=12.9.79=0
  - cuda-driver-dev=12.9.79=0
  - cuda-driver-dev_linux-64=12.9.79=0
  - cuda-libraries-dev=12.1.1=0
  - cuda-nvcc=12.1.105=0
  - cuda-nvrtc=12.9.86=0
  - cuda-nvrtc-dev=12.9.86=0
  - cuda-opencl=12.9.19=0
  - cuda-opencl-dev=12.9.19=0
  - cuda-profiler-api=12.9.79=0
  - cuda-version=12.9=3
  - expat=2.7.3=h7354ed3_4
  - ld_impl_linux-64=2.44=h153f514_2
  - libcublas=12.9.1.4=0
  - libcublas-dev=12.1.3.1=0
  - libcufft=11.4.1.4=0
  - libcufft-dev=11.4.1.4=0
  - libcufile=1.14.1.1=4
  - libcufile-dev=1.14.1.1=4
  - libcurand=10.3.10.19=0
  - libcurand-dev=10.3.10.19=0
  - libcusolver=11.7.5.82=0
  - libcusolver-dev=11.7.5.82=0
  - libcusparse=12.5.10.65=0
  - libcusparse-dev=12.1.3.153=0
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnpp=12.4.1.87=0
  - libnpp-dev=12.4.1.87=0
  - libnsl=2.0.0=h5eee18b_0
  - libnvjitlink=12.9.86=0
  - libnvjitlink-dev=12.9.86=0
  - libnvjpeg=12.4.0.76=0
  - libnvjpeg-dev=12.4.0.76=0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - ocl-icd=2.3.3=h47b2149_0
  - opencl-headers=2025.07.22=hfb20e49_0
  - openssl=3.0.18=hd6dcaed_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.51.0=h2a70700_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - addict==2.4.0
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - crcmod==1.7
      - cryptography==46.0.3
      - cycler==0.12.1
      - einops==0.8.1
      - filelock==3.14.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - idna==3.11
      - iopath==0.1.10
      - jinja2==3.1.6
      - jmespath==0.10.0
      - kiwisolver==1.4.9
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mmcv==2.2.0
      - mmengine==0.10.7
      - mmsegmentation==1.2.2
      - model-index==0.1.11
      - mpmath==1.3.0
      - networkx==3.4.2
      - ninja==1.13.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - opencv-python==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.3
      - ordered-set==4.1.0
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.3.3
      - pillow==12.0.0
      - platformdirs==4.5.1
      - portalocker==3.2.0
      - prettytable==3.17.0
      - psutil==7.1.3
      - pycocotools==2.0.11
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2023.4
      - pyyaml==6.0.3
      - regex==2025.11.3
      - requests==2.28.2
      - rich==13.4.2
      - safetensors==0.7.0
      - scipy==1.15.3
      - setuptools==60.2.0
      - six==1.17.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - termcolor==3.2.0
      - timm==1.0.22
      - tokenizers==0.15.2
      - tomli==2.3.0
      - torch==2.2.2+cu121
      - torchaudio==2.2.2+cu121
      - torchvision==0.17.2+cu121
      - tqdm==4.65.2
      - transformers==4.38.2
      - triton==2.2.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==1.26.20
      - wcwidth==0.2.14
      - yacs==0.1.8
      - yapf==0.43.0
prefix: /root/user/cs_tcci_penghai/miniconda3/envs/segearth
